# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [11]:
# Tu respuesta aquí
nombre = "Dubian"
edad = 24   

print('Hola, me llamo ' + nombre + ' y tengo ' + str(edad) + ' años.')

Hola, me llamo Dubian y tengo 24 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [12]:
numeros = [10, 25, 3, 47, 8, 15]
# Profe creame :)
# tu respuesta aquí
print (numeros[0] , numeros [5])
print(numeros[0:3])
numeros.append(99)
print(numeros)

10 15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [13]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6.0:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [14]:
# Tu respuesta aquí
Base = 5
Altura = 8

def calcular_area(base, altura):
    area = (base * altura) / 2
    return area 

print(calcular_area(Base, Altura))


20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [15]:
# Tu respuesta aquí
comprehension = [x*1 for x in range(1, 11)]
print(comprehension)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


---
## Parte 2 — NumPy

In [16]:
import numpy as np



**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [17]:
# Tu respuesta aquí
shape = (3, 4)
array_2d = np.zeros(shape)
print(array_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [21]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz = a.reshape(3, 4)

maximo = matriz.max()
minimo = matriz.min()
indice_max = np.unravel_index(matriz.argmax(), matriz.shape)



print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Posición del máximo:", indice_max)

Máximo: 12
Mínimo: 1
Posición del máximo: (np.int64(2), np.int64(3))


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [31]:
# Tu respuesta aquí
a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

suma = a + b
resta = a - b
multiplicacion = a * b


print("a:", a)
print("b:", b)
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)


a: [ 4 19  1  7 16]
b: [ 9 19  9 14  9]
Suma: [13 38 10 21 25]
Resta: [-5  0 -8 -7  7]
Multiplicación: [ 36 361   9  98 144]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [32]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_aprobadas = notas[notas >= 6]

print("Notas mayores o iguales a 6:", notas_aprobadas)

Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
